# Generated by Django 3.2 on 2022-02-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220212_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliverAt',
        ),
    ]
